server:
  port: 8080
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingsystem_userservice
    username: root
    password: 1234
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      